# Generated by Django 5.2.8 on 2025-11-29 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='bulk_predictions/')),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('results_file', models.FileField(blank=True, null=True, upload_to='prediction_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('gpa', models.FloatField()),
                ('completed_units', models.IntegerField()),
                ('internship_completed', models.CharField(max_length=3)),
                ('participation', models.CharField(max_length=10)),
                ('discipline_score', models.FloatField()),
                ('assignment_score', models.FloatField()),
                ('predicted_class', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('bulk_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='predictor.bulkprediction')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.FloatField()),
                ('completed_units', models.IntegerField()),
                ('internship_completed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('participation', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('discipline_score', models.FloatField()),
                ('assignment_score', models.FloatField()),
                ('predicted_class', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
